name: Ronna
markdown: redcarpet
pygments: true
github: https://www.github.com/ronna-s
about: I'm a developer and an architecht, interested in science, polytics and economics. I am a feminist with a personal goal to bring more women into the field and help them grow.
urls:
    - text: github
      url: https://github.com/ronna-s
